export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main>
      <div className='container mx-auto max-w-md'></div>
    </main>
  );
}
